### ISSUE TITLE
Cannot use multiple private repos

### ISSUE THREAD

**Issue by evok01** [php-actions/composer#10]
The solution to pull down a private repo is working great, but my problem is that since Github does not allow you to share deploy keys across repos, this solution is only working if you have a single private repository.

Is is possible to supply `ssh_key` more than once?

I might be missing something about how to re-use a public key as a deploy key, but at the moment I don't see it.

**Comment by evok01** [comment]
Stupid me, nevermind.

I was just able to create a machine using and instead of setting a deploy key, I just added that as an SSH key for that user.

**Comment by g105b** [comment]
That's great to hear. Do you think I could improve the documentation at all to help others in your position?

**Comment by evok01** [comment]
Sorry to get back so late. It certainly would not hurt to have a reminder that there is such a thing as ssh keys for a user account, that way someone doesn't have to bother you about it... like I did :)

**Comment by g105b** [comment]
No problem. I'll give the docs another thought at some point.

**Comment by noknokcody** [comment]
Hi there, just come across the same issue so maybe worth updating the doco if you get a chance. Thanks!
