### ISSUE TITLE
PHP 8.2

### ISSUE THREAD

**Issue by cmahnke** [php-actions/composer#101]
PHP 8.2 isn't mentioned (yet) in the docs as a possible setting for `php_version`

**Comment by g105b** [comment]
I *think* this is just the docs not being updated, as the available PHP versions are taken from the PHP docker hub, but I'll check, and update the docs accordingly. Thanks for your issue report.

**Comment by g105b** [comment]
Thanks again. Docs are always really important, I've added clarification now.
