### ISSUE TITLE
No longer working with SVG files - syntax error near unexpected token `newline'

### ISSUE THREAD

**Issue by DenverCoder1** [php-actions/composer#105]
As of July 30, the action has been working, but today failed without any changes to the code or action.

The error seems to imply it has to do with a file containing `<?xml version="1.0" encoding="utf-8"?>` which would be an SVG file, not PHP.

Output:

```
Run php-actions/composer@v6
Run set -e
  set -e
  bash <(curl -s https://raw.githubusercontent.com/php-actions/php-build/cee5b9fa9fbc4c888e7a62bbb7b8eade18e3c56b/php-build.bash) composer
  /home/runner/work/_actions/php-actions/composer/v6/composer-action.bash
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    ACTION_VERSION: latest
    ACTION_PHP_VERSION: latest
    ACTION_COMMAND: install
    ACTION_INTERACTION: no
    ACTION_DEV: yes
    ACTION_PROGRESS: no
    ACTION_QUIET: no
/dev/fd/63: line 2: syntax error near unexpected token `newline'
/dev/fd/63: line 2: `<?xml version="1.0" encoding="utf-8"?>'
Error: Process completed with exit code 2.
```

https://github.com/DenverCoder1/readme-typing-svg/actions

**Comment by DenverCoder1** [comment]
Updating to the latest commit hash resolved the issue

`php-actions/composer@9357db0fb3020086db5a9922354c8dc643927bcd`

Maybe a new tagged version needs to be released?

**Comment by g105b** [comment]
Hi @DenverCoder1,

No changes have been made to the repository for a while, so I'm interested into investigating the cause of this.

Thanks for reporting the issue, have a nice day!

Greg.
