### ISSUE TITLE
Troubles when working_dir is specified

### ISSUE THREAD

**Issue by andradedpg** [php-actions/composer#16]
Hy everyone!
 In my repository, composer.json isn't on the root level. I have somelike that: 

```
 - another_folder
 - configs.file
 - src 
  - [...]
  - composer.json 
```

 When I set working_dir on my actions to **working_dir: ./src**, I received:
  
`Warning: Unexpected input(s) 'working_dir', valid inputs are ['entryPoint', 'args', 'command', 'only_args', 'interaction', 'suggest', 'dev', 'progress', 'quiet', 'ssh_key', 'ssh_key_pub', 'ssh_domain']`
 
 But, in https://github.com/php-actions/composer/blob/master/action.yml we have the specification between lines 54 and 56:

 `working_dir:
    description: Use the given directory as working directory
    required: false`

Im unsure about what will be behavior expected from that parameter. Maybe just Im in wrong way.
Thanks in advanced!

**Comment by g105b** [comment]
Hi @andradedpg , you were just a bit too quick for the `working_dir` input as it's only just been added as a supported feature. Check [the latest commit](https://github.com/php-actions/composer/commit/419c21f48a42a1c51d5b297a92623d0a7faa7f02) which was made only 1 day before you raised the issue.

The functionality is now part of the v3 release. Please let me know how you get on with it and if you have any problems, I'll jump on them to fix.

**Comment by Anthodev** [comment]
It seems you made a typo in this feature on line 36, can you release a quickfix please @g105b?

`command_string="$command_string --working-dir=$action_working_dir"`

Instead of :
`command_string="$command string --working-dir=$action_working_dir"`

The typo give me the following error when a job runs :
```
/usr/local/bin/entrypoint: line 118: string: command not found
Command:  string --working-dir=./[*hidden*] --no-interaction
```
