### ISSUE TITLE
Set up fails

### ISSUE THREAD

**Issue by chris-kruining** [php-actions/composer#2]
I get a failure in the set up stage with a 404 error, I copied the example config from https://github.com/g105b/phpspec-example. Did I do some thing wrong?
Failed run :: 
https://github.com/chris-kruining/utilities/commit/eb7d6b915f877e60884fd20c323edaf4ecf85d1a/checks?check_suite_id=315904163

**Comment by g105b** [comment]
Yep - `phpactions` should be `php-actions` :)

**Comment by chris-kruining** [comment]
fixed

**Comment by g105b** [comment]
Great to hear. Let me know how you get on.
