### ISSUE TITLE
Build failing because of non existent arguments

### ISSUE THREAD

**Issue by Danon** [php-actions/composer#21]
I tried running `composer test` with php-actions/composer@v1 and @v2, and in both cases I got this error:

```
Command: composer test --no-interaction --no-suggest --no-progress

Error: The "--no-suggest" option does not exist.
```
![image](https://user-images.githubusercontent.com/13367735/98440547-aa3cf800-20f9-11eb-9065-6ca6ae48dbf6.png)

I get the same version on my local compose in versions 1.9 and 2.0.6.

I'm buffled as to why actions try to run compoer with invalid arguments?

**Comment by g105b** [comment]
Hi @Danon , please could you confirm that this issue is dived on `php-actions/composer@master`? It's something I've fixed [in this commit](https://github.com/php-actions/composer/commit/f006b92b09bcfc358aea006bf2379785912f0abc) recently but will need to be made into a release.

**Comment by Danon** [comment]
After I've upgraded to @v3 it works. Thank you.

**Comment by g105b** [comment]
Aha, excellent - I'm in the middle of putting together a version of this action that can switch PHP versions and Composer versions, I had forgotten the release was already out there.
