### ISSUE TITLE
No action argument available to change php or composer version

### ISSUE THREAD

**Issue by hunomina** [php-actions/composer#22]
The only way to change php or composer version now is by using environment variables. 
It would be nice to have action arguments for that.

**Comment by g105b** [comment]
Hey @hunomina , you're in luck. I'm literally building this feature right now and you can test it by switching to the master branch.

See here: https://github.com/php-actions/composer/blob/master/action.yml#L4-L12

I'll let you know here when things are released and documented.

**Comment by g105b** [comment]
Oh, I see from your PR that you already knew this, and have passed them through to the entrypoint. Thanks so much for your contribution. This is one less thing for me to do today!
