### ISSUE TITLE
Proper caching

### ISSUE THREAD

**Issue by szepeviktor** [php-actions/composer#25]
Please do not encourage users to cache vendor directory.

`path: vendor/`

It makes CI unpredictable.

BTW `::set-output` is unused in README.

**Comment by g105b** [comment]
Hi @szepeviktor ,

I considered the caching of the vendor directory a useful feature (as long as the cache is validated against the composer.lock file). Please can you suggest an alternative method of doing this?

The documentation of https://github.com/actions/cache was used when forming my opinion of caching the vendor directory (the example uses the `node_modules` directory of an NPM project instead.

**Comment by szepeviktor** [comment]
I'm not able to convince you that only the cache directory should be actually cached.
https://github.com/travis-ci/travis-ci/issues/4579#issuecomment-127972205

Composer can install packages from the cache to `/vendor` directory in 1 second!
In theory it applies also for npm, in reality npm is viktor-blacklisted, please consider using Yarn v1/v2.

**Comment by szepeviktor** [comment]
> Please can you suggest an alternative method of doing this?

Please see this PR https://github.com/php-actions/composer/pull/26

**Comment by g105b** [comment]
This is great, thanks very much. I'll check it out and merge the PR once tested.

**Comment by g105b** [comment]
Thanks. Merged #26.

**Comment by szepeviktor** [comment]
You're welcome.
