### ISSUE TITLE
404: Failed to download action

### ISSUE THREAD

**Issue by BrianHenryIE** [php-actions/composer#3]
https://github.com/BrianHenryIE/BH-WP-Autologin-URLs/commit/2cd7a8885971128ed54d18e8249648301f5dc67f/checks?check_suite_id=396092251

I had to change:

```
- uses: php-actions/composer@v1
```
to
```
- uses: php-actions/composer@master
```

I also tried `@1.0.0` with no luck.

**Comment by g105b** [comment]
Thanks for the report. I'll look into this and adjust the docs when I get back to my computer tomorrow.

**Comment by gurban-h** [comment]
Tag is named as `v1.0.0` rather than `v1` (https://github.com/php-actions/composer/releases). So it works when you use
```
- uses: php-actions/composer@v1.0.0
```

**Comment by g105b** [comment]
Thank you! I'll update the docs so this can be avoided in the future.

**Comment by g105b** [comment]
I have made another tag called `v1` as this is more consistent with other Github Actions versioning and does not require any changes to documentation.

Thanks for pointing this out.
