### ISSUE TITLE
Installing action is horribly slow

### ISSUE THREAD

**Issue by andig** [php-actions/composer#35]
See https://github.com/andig/carddav2fb/pull/220/checks?check_run_id=1581471294 for an example. The installation of the action (not the actual dependencies) takes 2 minutes alone. Not sure if I've misconfigured, but installing the action should be more or less instantaneous?

**Comment by g105b** [comment]
Hi @andig,

You have not misconfigured, but please see this test run: https://github.com/PhpGt/Database/actions/runs/431015623

The build step (composer) takes 18s to build the action and install the dependencies. This is using a new version of the action, which is currently being developed to overcome some limitations. I don't think there is anything more to complete before a stable release is made, but please could I ask you to test this for me on your repository?

Check out the [PhpGt/Database ci.yml](https://github.com/PhpGt/Database/blob/master/.github/workflows/ci.yml) to see how I'm using it on that repository, but basically you need to change from using `v4` to using the pre-released [`dynamic-docker` branch](https://github.com/PhpGt/Database/blob/master/.github/workflows/ci.yml#L11).

I'll leave this issue open until the release is made, but before then I will be testing on my own repositories and will appreciate any feedback you can provide from your repositories.

Thanks,
Greg.

**Comment by andig** [comment]
Confirmed working and lightning fast :)

**Comment by g105b** [comment]
Great! Very glad to hear it. It's been a big learning curve for me to get Github Actions working on my side, but I'm really happy with how it's working now, so if you have any feedback or ideas I'd love to hear them.

Cheers.

**Comment by g105b** [comment]
Released into v5 :)
