### ISSUE TITLE
Automatically created docker packages after using this action

### ISSUE THREAD

**Issue by jan-di** [php-actions/composer#36]
Hello, 
Today I've tested this action. While it works, I was surprised that the repo now shows two packages related to the php-actions: 
![grafik](https://user-images.githubusercontent.com/23323185/103460781-70632900-4d19-11eb-914f-6a6a887a4e81.png)
https://github.com/jan-di?tab=packages&repo_name=php-config

I've only run a single workflow that seems to created them (I've used the composer action and the phpunit action):
https://github.com/jan-di/php-config/runs/1636637449?check_suite_focus=true

Is this a known behaviour? And do you know how I can delete those packages?

**Comment by g105b** [comment]
Hi @jan-di ,

This is known behaviour as of v5. To achieve the build speeds and configuration possibilities, the custom Docker image is pushed to the repository that calls the action. This means that your user or organisation will list the package on the page at https://github.com/{organisation}/packages. This shouldn't have any effect on things, but it's worth knowing about.

If this wasn't done, the build times would be significantly longer. There may be a better alternative to how/where the images are pushed. If you have any ideas, please let me know. Is this a problem for you?

To delete the images, you can click on the package in the organisation's packages list, then go to edit package, manage versions, then click the delete button next to the version you wish to delete.

Thanks,
Greg.

**Comment by jan-di** [comment]
Thanks for the explanation. It makes sense, its just that I haven't expected the packages to be there. Technically it isn't a problem, I just think it is misleading for users of the repository, because the package does not refer to the content of the repository itself. 

The problem is, that I don't have the UI available you described. It works only for containers in the new container registry (ghcr.io), at least I can reproduce that with another docker contaioner built by myself. For the mentioned package this issue is about there is no possibility to delete versions. It seems that this is intended, see https://docs.github.com/en/free-pro-team@latest/packages/manage-packages/deleting-a-package#about-public-package-deletion

I guess I will reach out the GitHub support and see if they could delete them. For this repository, maybe there should be a Hint in the Readme that the action caches itself as a package, to make the behaviour you described more transparent.

Thanks, anyways :)

**Comment by g105b** [comment]
I have an idea. You can temporarily switch your repository to private to get the UI you need to delete, then switch back to public. I don't understand why GitHub would choose to hide the UI, even when you can delete a public repo just fine.

The problem with the new GitHub package repository is that it isn't compatible with public write access, so it would be a requirement of the developer to generate and send a personal access token just to use this composer action... Again, if you have any ideas on how to improve this, I'd love to hear them.

Take care,
Greg.
