### ISSUE TITLE
v5 denied: Resource not accessible by integration

### ISSUE THREAD

**Issue by Tigerman55** [php-actions/composer#39]
I started getting this error since v5 was updated. Before the update, I was receiving the cloning private repository error that was fixed.

`denied: Resource not accessible by integration`

Also another error in the console:

`Error response from daemon: manifest for docker.pkg.github.com/myorganization/mywebsite.com/php-actions_composer_mywebsite.com:php-7.4-build2 not found: manifest unknown: Docker image reference php-actions_composer_mywebsite.com:php-7.4-build2 not found under repo "myorganization"`

If I execute my build on v4 everything runs correctly.

**Comment by g105b** [comment]
Hi @Tigerman55,

Thanks for reporting this issue. I'm not sure what can be causing this but I'll look into fixing it. Please see https://github.com/php-actions/example-composer which has a CI step that loads a private repository.

I'm not sure what the `denied` error is referencing, but the `manifest for docker ... not found` is expected the first time you run the action after an update (the action will rebuild and push, then the manifest will be found).

Is your repository open/closed source? If it's open, can you share it with me? If it's closed, is there a way you can share the config yml?

**Comment by Tigerman55** [comment]
It's a private repository, but I'd be glad to share the config .yml.

https://gist.github.com/Tigerman55/cc43c3be7342768eb60ae9011ddcd3f3

**Comment by g105b** [comment]
Hi @Tigerman55 ,

I've just created a private repository to test this: https://github.com/g105b/test-tigerman55

You should have an invite to collaborate. The repo requires 1 public and 1 private composer package, and it installs using the action without any issue. If you check the action runs, you'll see I created the ci.yml file first, which failed due to there being no composer.json, then on the second commit I added the composer.json and composer.lock file, and using a very similar config to yours, the action succeeded.

I'll happily try and help solve why this isn't working for you. Let me know what you think we could try to isolate your issue.

Greg.

**Comment by g105b** [comment]
Here are some screenshots that might help others that don't have access to the test private repo:

***

composer.json:

![image](https://user-images.githubusercontent.com/358014/104030846-ec4eec80-51c3-11eb-9b88-9b909775067c.png)

***

Github workflow:

![image](https://user-images.githubusercontent.com/358014/104030910-01c41680-51c4-11eb-80cb-d3e847435aa0.png)

***

List of actions that have run:

![image](https://user-images.githubusercontent.com/358014/104030971-130d2300-51c4-11eb-9dbe-d4c4ffd326cb.png)

***

Composer logs (completed successfully in 10 seconds)

![image](https://user-images.githubusercontent.com/358014/104031047-2a4c1080-51c4-11eb-99d7-612eb34e694e.png)

***

Hope this helps someone.

**Comment by Tigerman55** [comment]
I just discovered that using repository of type "github" in composer is what was causing this error. When I switched it to vcs, the error disappeared. I still have no idea why that would cause it. Are you aware of what might cause that behavior?

**Comment by Tigerman55** [comment]
As a reference. Before, my composer.json key syntax was this:

`"repositories": [
    {
      "type": "github",
      "url": "git@github.com:organization/reponame.git"
    }
]`

Now, this works:

`"repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/organization/reponame"
    }
]`

**Comment by g105b** [comment]
Strange, [according to the Composer documentation](https://getcomposer.org/doc/04-schema.md#repositories), only the types `vcs`, `composer` or `package` are supported.

**Comment by g105b** [comment]
Is everything working for you now?

**Comment by Tigerman55** [comment]
It is possible that the option was removed in composer v2. Yes, it is working perfectly now.

**Comment by g105b** [comment]
Great to hear. Always happy to help in the future.
