### ISSUE TITLE
Any specific reason why this doesn't call the script directly?

### ISSUE THREAD

**Issue by paras-malhotra** [php-actions/composer#44]
Instead of this:

https://github.com/php-actions/composer/blob/ff923f6d2bca1f888115c734de8cc64147bb2abc/action.yml#L93-L95

Can't we simply do [this](https://github.community/t/running-a-bash-script/141584)?

**Comment by paras-malhotra** [comment]
Nvm I need some sleep 😆

**Comment by g105b** [comment]
The curl redirection is there to allow for the base php image to be maintained in another repository, so this repository can contain all of its logic within the `composer-action.bash` file.

Happy to discuss how it works or alternative approaches if you want.

**Comment by paras-malhotra** [comment]
Yeah my bad, sorry for the bother. I thought it was downloading the bash file that already exists in the repo.
