### ISSUE TITLE
Dockerfile conflict on first run

### ISSUE THREAD

**Issue by saernz** [php-actions/composer#46]
I think I have found a bug where this action overwrites my Dockerfile when building it's own Dockerfile. My Dockerfile exists in the root of the project and from looking at the source code this action appears to overwrite it.

I always get a fail on my first run when using this action when trying to run tests. This appears to be caused when I try to build my own Dockerfile, though instead of building my Dockerfile it appears it builds this actions Dockerfile instead which is why my tests fail.

To test this I make sure this actions container has been cleared before running the action by going into the repos packages page, selecting the generated container, then clicking on Package settings and deleting it. Then upon running my workflow again it will fail because of this conflict. Subsequent reruns of the workflow do not fail as the image already exists.

I wonder if this could be fixed by writing the Dockerfile to a temp directory or even just piping it to stdin: https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#pipe-dockerfile-through-stdin

**Comment by g105b** [comment]
Hi @saernz ,

You've identified a bug. I'm actually making another bugfix this afternoon so I'll aim to fix this in the same release. Because it's a fix rather than a feature, I'll be releasing this into `v5`.

**Comment by g105b** [comment]
I've just released a patch to v5 that fixes this issue. Sorry that it wasted some of your time, let me know how you get on.

Greg.
