### ISSUE TITLE
Install deps on a subdirectory

### ISSUE THREAD

**Issue by adamgen** [php-actions/composer#50]
I'm trying to install on a subdirectory using 

```
args: --profile --ignore-platform-reqs --working-dir=$GITHUB_WORKSPACE/wp
```

But with no success, the $GITHUB_WORKSPACE is not parsed. Any idea on what can be done?

**Comment by adamgen** [comment]
Just using 

```
args: --profile --ignore-platform-reqs --working-dir=wp
```

works fine...

**Comment by jmartsch** [comment]
I think these instructions should be in the readme as an example

**Comment by g105b** [comment]
Hi @jmartsch I agree. I'll put this on my todo list for later this week, but happy to receive any pull requests adding this detail to the readme.
