### ISSUE TITLE
Incompatible with ACT local GH Action runner

### ISSUE THREAD

**Issue by gitromba** [php-actions/composer#54]
It would be great if this action could be working locally with [ACT](https://github.com/nektos/act) so you can avoid the cumbersome commit-push verification. 

For the  moment this is the error message I receive:
```
[Code verification/build]   ❌  Failure - Install dependencies
Error: The runs.using key in action.yml must be one of: [docker node12], got composite
```

**Comment by g105b** [comment]
Hi @gitromba ,

Thanks for your suggestion. This repository uses a composite action runner, which has been a feature of GitHub Actions for a while now.

So maybe this issue should be redirected to ACT so that project can be made compatible?

**Comment by g105b** [comment]
This issue is already tracked here: https://github.com/nektos/act/issues/607

**Comment by gitromba** [comment]
Indeed it would rather make sense having it fixed in ACT 🤞.

Thank you and keep up the awesome work with `php-actions/composer` 🚀
