### ISSUE TITLE
Missing output.log file

### ISSUE THREAD

**Issue by rizvisx** [php-actions/composer#55]
Complains of this
cat: /home/runner/work/xyz/project/output.log: No such file or directory

**Comment by g105b** [comment]
Hi @rizvisx ,

Please see the [Example Composer repository](https://github.com/php-actions/example-composer) which I use as a sandbox for demonstrating how to use this action.

In the CI.yml, we pass the `output.log` file to the `upload-artifact` action, so we can analyse the output through Github's web interface. See here: https://github.com/php-actions/example-composer/blob/check-output/.github/workflows/ci.yaml#L22

Then, we can download the artifact here: https://github.com/php-actions/example-composer/actions/runs/789885119 (see `debug-output` link near the bottom of the page).

I hope this shows that the `output.log` file is indeed present on the action runner, but I'm happy to help diagnose your issue further. Are you aware that files are not persisted between the different steps of your workflow, without manually uploading them as an artefact?

Cheers,
Greg.

**Comment by g105b** [comment]
Hi again...

I made another example workflow that simply does `cat /home/runner/work/example-composer/example-composer/output.log`.

You can see the workflow running here: https://github.com/php-actions/example-composer/runs/2450332073?check_suite_focus=true

![image](https://user-images.githubusercontent.com/358014/116284655-39f86080-a785-11eb-8414-293a43e53306.png)

The workflow is defined here: https://github.com/php-actions/example-composer/blob/master/.github/workflows/ci-show-output-log.yml

I hope this helps you! If you are still having problems, please feel free to reopen this issue - I'm happy to help.

Greg.

**Comment by rizvisx** [comment]
Hi @g105b 

I should have been more descriptive with my question. 
The error shown below shows up in the composer action, and it doesn't show any more details even with `--verbose` set.

`
Run php-actions/composer@v5
  with:
    progress: yes
    args: --verbose
    version: latest
    php_version: latest
    command: install
    interaction: no
    dev: yes
    quiet: no
cat: /home/runner/work/my-project/my-project/output.log: No such file or directory
Error: Process completed with exit code 1.
`
So, it doesn't reach to next steps i.e.  Upload artifacts or check contents of output.log


Thanks for quick reply !!

**Comment by g105b** [comment]
Can you compare your workflow yml file with the know working files in the example composer repository and see any difference in configuration?
