### ISSUE TITLE
Docs not updated

### ISSUE THREAD

**Issue by euberdeveloper** [php-actions/composer#68]
The default version is now 8, right?

**Comment by g105b** [comment]
Hey, yeah the default PHP version is currently 8.0. I'll update this in the docs when I next get chance on open source stuff - unless you want to help me out with this little update?

Cheers,
Greg.

**Comment by euberdeveloper** [comment]
Done

**Comment by EQuimper** [comment]
@g105b Do you know if you will update it to 8.1 which was release yesterday ?

**Comment by g105b** [comment]
Good question @EQuimper - I think we should always link `latest` to whatever the latest release is. I'll merge @euberdeveloper 's PR in later, but in the meantime maybe they will be able to sneak an extra commit to update it to 8.1?

**Comment by euberdeveloper** [comment]
I close the issue since the pr was merged
