### ISSUE TITLE
Not able to authenticate with private repos

### ISSUE THREAD

**Issue by pridit** [php-actions/composer#7]
Hi, I'm trying to pull in a private repository. I have added the SSH key through a different GitHub action. I have also tested cloning the private repo straight after which is fine, which means it's picking up the SSH key as expected, however when it finally gets around to the install I'm met with:
```
Host key verification failed.
fatal: Could not read from remote repository.
```
Is there something I'm missing?

**Comment by g105b** [comment]
Simply put, this error is from Git and means the SSH key being used is not authorised for the repository you're trying to access. My first thought is that the SSH key file isn't placed in the right location, but I can't advise much more without seeing for myself.

I will make a private repository and see if I can clone it in a test repo and report back here. In the meantime, try to debug where the SSH key is being added from a previous Action, and be aware that different jobs run in isolation from each other.

**Comment by pridit** [comment]
As mentioned I have confirmed that I can clone the repository, which is also the same repository that composer is trying to pull down - which means the key is authorized. This could be to do with isolation, so could it just be the case that the `Dockerfile` needs to be updated to copy in the SSH key and the `known_hosts` file added in the previous Action? [This is the Action I'm using](https://github.com/shimataro/ssh-key-action).

Failing that how am I supposed to get composer to use my SSH key when using this Action? I'm bringing these workflows over from Bitbucket Pipelines so there's a bit of a learning curve for me here.

**Comment by g105b** [comment]
Please could you share the Github repository that is using the ssh-key-action, so I can inspect the action logs? If it's a private repo, no worries, I'm still planning on running a test myself to help resolve this.

**Comment by pridit** [comment]
I have set up an example repository and reproduced this here: https://github.com/pridit/php-actions-composer-test/runs/661123569

**Comment by g105b** [comment]
Thanks. This will help when I get to look into this. In the meantime, would you mind changing the example repo to put the keys in ~/.ssh rather than explicitly setting the path to /home/runner/.ssh ? It's just the first thought off the top of my mind.

**Comment by pridit** [comment]
I think `runner` is just the user GitHub uses when running workflows? This hasn't been set explicitly from my end. https://github.com/shimataro/ssh-key-action/blob/v2/src/main.ts#L52

**Comment by g105b** [comment]
OK that's fine then. Two more ideas have come to mind. I know that certain SSH clients do not allow the key to be unprotected. Can you ensure that the key files (private public key pairs) are in the .ssh directory with only read access from the owner? Secondly, I wonder if you could explain to me the lowercase "o" in the permission: https://github.com/shimataro/ssh-key-action/blob/v2/src/main.ts#L56 - this is something that I don't understand (what data type is this), so it might be obvious, but it's something that sticks out to me and is worth investigating.

**Comment by lokisapocalypse** [comment]
I too am having this exact issue. Is there an example config that shows how to authenticate against a private repo?

**Comment by g105b** [comment]
@lokisapocalypse good idea. I will create an example project that does exactly this.

**Comment by g105b** [comment]
@pridit your issue is now fixed and documented in v2 of this repository. Please let me know how you get on.

@lokisapocalypse I have implemented an example project here: https://github.com/php-actions/example-composer and this repository depends on a private project. Check out the Actions tab to see it installing perfectly.

Hope everything makes sense for everyone, I'm happy that I've finally got some time to look into this for you.
