### ISSUE TITLE
Composer oauth no longer supported?

### ISSUE THREAD

**Issue by ndench** [php-actions/composer#72]
PR #29 added support for composer oauth in Dec 2020, but it no longer appears to be supported. I can't seem to find any record of it being removed or why. Was this intentional?

**Comment by g105b** [comment]
This was not intentional. I will look into the reason as soon as I get to open source after Christmas. Thanks for raising the issue.

**Comment by g105b** [comment]
Please revisit this functionality if you're still interested. I can see some other users are successfully using an oauth token, and @execut kindly provided simpler instructions of usage. Feel free to re-open if you're having any issues.
