### ISSUE TITLE
GitHub are deprecating the `set-output` command in actions

### ISSUE THREAD

**Issue by markbeazley** [php-actions/composer#92]
See [this announcement](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/), currently still working, but is throwing this `Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/` in the actions log.

**Comment by g105b** [comment]
Thank you! I'll look into what needs to be changed.

**Comment by agaengel** [comment]
I think this would be fixed by #93

**Comment by g105b** [comment]
#92 is now merged. Feedback is appreciated.

**Comment by markbeazley** [comment]
@g105b Brilliant thanks, that seems to have worked on our repos workflow.
