### ISSUE TITLE
Running in a different directory

### ISSUE THREAD

**Issue by uuf6429** [php-actions/composer#96]
Due to the stupid situation in https://github.com/actions/checkout/issues/197, I need to run this action in a different directory.

Is this possible?

Long story: Some of my packages' workflow depends on other composer packages "downloaded"(checked out) as git repositories.
The 'main' composer.json (of the package being tested) points to the other packages as local "path" repositories (in composer lingo).
Since I can't check them out in the parent directory (due to the problem mentioned above) the next option is to have everything in the "current"/"workspace" directory and execute the composer action in a sub-directory.

The only solution I found is to check out the repo in the current repo, which works for the workflows but causes a lot of trouble locally.

----

Consider that we have projects `p1` and `p2` and that we want to test `p2`, which depends on `p1`.

**option 1:**
- check out contents of p2 **into** current directory (`/workspace`)
- check out p1 in parent directory (`/p1`) - (not possible because of https://github.com/actions/checkout/issues/197)
- run actions as usual (in `/workspace`)

**option 2:**
- check out p2 in current directory (`/workspace/p2`)
- check out p1 in current directory (`/workspace/p1`)
- run actions in `/workspace/p1` - (maybe possible, depends on this issue's answer(s))
_maybe not ideal, if the "custom path" feature needs to be supported by all actions_

**option 3:**
- check out contents of p2 **into** current directory (`/workspace`)
- check out p1 also in the current directory (`/workspace/p1`)
- run actions as usual (in `/workspace`)
_this is not ideal due to conflicts and complicates local development_

**Comment by uuf6429** [comment]
I remembered that composer has this feature already, so I'll go with it:
```yaml
      - name: Set up PHP
        uses: php-actions/composer@v6
        with:
          command: install
          args: --working-dir my-project
```

**Comment by g105b** [comment]
Glad you've found a solution. Do you think this repo could be improved at all to help your needs?
